version: "3"
services:
  redis:
    image: redis
    ports:
      - '6379'
  web:
    build: .
    command: bundle exec ruby app.rb -o 0.0.0.0
    volumes:
      - .:/sinatra-sample-app
    ports:
      - '4567:4567'
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
